### ISSUE TITLE
Flatpak runtime branch is EOL, please update

### ISSUE THREAD

**Issue by Scotty-Trees** [flathub/de.zwarf.picplanner#8]
Currently on Fedora 41, Gnome 47 and after running `flatpak update` I came across this warning. Please update to the lastest flatpak runtime, thank you. 

```
Looking for updates…

Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
de.zwarf.picplanner
```

**Comment by zwarf12** [comment]
Thanks a lot for letting me know.
Finally made all the changes. Update is merged.
[v0.5.1](https://github.com/flathub/de.zwarf.picplanner/pull/10)
